%YAML 1.1
// Upgrade NOTE: excluded shader from DX11, OpenGL ES 2.0 because it uses unsized arrays
#pragma exclude_renderers d3d11 gles
%TAG !u! tag:unity3d.com,2011:
--- !u!114 &1
MonoBehaviour:
  m_ObjectHideFlags: 61
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 12501, guid: 0000000000000000e000000000000000, type: 0}
  m_Name: New Graph
  m_EditorClassIdentifier: UnityEditor.dll::Unity.GraphToolkit.Editor.Implementation.GraphObjectImp
  m_GraphModel:
    rid: 233707230134272007
  references:
    version: 2
    RefIds:
    - rid: -2
      type: {class: , ns: , asm: }
    - rid: 233707230134272007
      type: {class: GraphModelImp, ns: Unity.GraphToolkit.Editor.Implementation, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Guid:
          m_Value0: 3613895897157463711
          m_Value1: 2067602197495092782
        m_HashGuid:
          serializedVersion: 2
          Hash: 9fee4fd52b2327322e1683763e99b11c
        m_Name: 
        m_GraphNodeModels:
        - rid: 233707230134272640
        - rid: 233707230134272726
        - rid: 233707275728453644
        - rid: 233707275728454029
        m_GraphWireModels:
        - rid: 233707275728454030
        - rid: 233707275728454037
        - rid: 233707275728454038
        - rid: 233707275728454041
        m_GraphStickyNoteModels: []
        m_GraphPlacematModels: []
        m_GraphVariableModels:
        - rid: 233707275728454027
        m_GraphPortalModels: []
        m_SectionModels:
        - rid: 233707230134272008
        m_LocalSubgraphs: []
        m_LastKnownBounds:
          serializedVersion: 2
          x: 372
          y: 493
          width: 937
          height: 236
        m_GraphElementMetaData:
        - m_Guid:
            m_Value0: 18052564638043145595
            m_Value1: 6207819919762491981
          m_HashGuid:
            serializedVersion: 2
            Hash: 7b055747e49787fa4d8a099b539b2656
          m_Category: 0
          m_Index: 0
        - m_Guid:
            m_Value0: 15812093756394153039
            m_Value1: 13382450805772240484
          m_HashGuid:
            serializedVersion: 2
            Hash: 4fa40bd17ed76fdb64c631c61a04b8b9
          m_Category: 0
          m_Index: 1
        - m_Guid:
            m_Value0: 5123283793393491998
            m_Value1: 3031436441729121255
          m_HashGuid:
            serializedVersion: 2
            Hash: 1e20bc3c778f1947e73b70ec61d3112a
          m_Category: 0
          m_Index: 2
        - m_Guid:
            m_Value0: 8632439709971575005
            m_Value1: 13596975365777691978
          m_HashGuid:
            serializedVersion: 2
            Hash: ddf0d4f92d96cc774a95ea280e29b2bc
          m_Category: 1
          m_Index: 0
        - m_Guid:
            m_Value0: 17751357266449895811
            m_Value1: 4258246029320837714
          m_HashGuid:
            serializedVersion: 2
            Hash: 8391cb13627d59f652dae2d73354183b
          m_Category: 0
          m_Index: 3
        - m_Guid:
            m_Value0: 11251167019528449417
            m_Value1: 9742502661056021043
          m_HashGuid:
            serializedVersion: 2
            Hash: 896d9503cb2c249c33c28a5f8d523487
          m_Category: 2
          m_Index: 0
        - m_Guid:
            m_Value0: 17954972606505202075
            m_Value1: 5528928171543745782
          m_HashGuid:
            serializedVersion: 2
            Hash: 9bb19cc274e02cf9f6d483e5e0b2ba4c
          m_Category: 2
          m_Index: 1
        - m_Guid:
            m_Value0: 17013978429587401452
            m_Value1: 17852264745276625699
          m_HashGuid:
            serializedVersion: 2
            Hash: ec2ab7df3ccb1dec2353715233fcbff7
          m_Category: 2
          m_Index: 2
        - m_Guid:
            m_Value0: 4855327528933556453
            m_Value1: 1830235595650083997
          m_HashGuid:
            serializedVersion: 2
            Hash: e58042b6a99661439dacffc5934d6619
          m_Category: 2
          m_Index: 3
        m_EntryPoint:
          rid: 233707230134272640
        m_Graph:
          rid: 233707230134272009
    - rid: 233707230134272008
      type: {class: SectionModel, ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Guid:
          m_Value0: 7653384932907528896
          m_Value1: 10659410744384860479
        m_HashGuid:
          serializedVersion: 2
          Hash: c0b2470f0c49366a3fb10a9698d5ed93
        m_Version: 2
        m_Items:
        - rid: 233707275728454027
        m_Title: 
    - rid: 233707230134272009
      type: {class: ComputeGraph, ns: Editor, asm: ComputeGraph.Editor}
      data:
        guid: d0e5cb85-1c48-48ff-9c28-784e9a5fcda4
        computeShader: {fileID: 0}
    - rid: 233707230134272640
      type: {class: UserNodeModelImp, ns: Unity.GraphToolkit.Editor.Implementation, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Guid:
          m_Value0: 18052564638043145595
          m_Value1: 6207819919762491981
        m_HashGuid:
          serializedVersion: 2
          Hash: 7b055747e49787fa4d8a099b539b2656
        m_Version: 2
        m_Position: {x: 1121.0507, y: 493.19336}
        m_Title: 
        m_Tooltip: 
        m_NodePreviewModel:
          rid: -2
        m_State: 0
        m_InputConstantsById:
          m_KeyList:
          - Index
          - Value
          - RWBuffer
          m_ValueList:
          - rid: 233707230134272643
          - rid: 233707326315429888
          - rid: 233707326315429889
        m_InputPortInfos:
          expandedPortsById:
            m_KeyList: []
            m_ValueList: 
        m_OutputPortInfos:
          expandedPortsById:
            m_KeyList: []
            m_ValueList: 
        m_Collapsed: 0
        m_CurrentModeIndex: 0
        m_ElementColor:
          m_Color: {r: 0, g: 0, b: 0, a: 0}
          m_HasUserColor: 0
        m_Node:
          rid: 233707230134272645
    - rid: 233707230134272643
      type: {class: 'Constant`1[[System.Int32, mscorlib]]', ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Value: 0
    - rid: 233707230134272645
      type: {class: WriteBuffer, ns: Editor.Nodes.Buffers, asm: ComputeGraph.Editor}
      data: 
    - rid: 233707230134272726
      type: {class: UserNodeModelImp, ns: Unity.GraphToolkit.Editor.Implementation, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Guid:
          m_Value0: 15812093756394153039
          m_Value1: 13382450805772240484
        m_HashGuid:
          serializedVersion: 2
          Hash: 4fa40bd17ed76fdb64c631c61a04b8b9
        m_Version: 2
        m_Position: {x: 550.74097, y: 613.3609}
        m_Title: 
        m_Tooltip: 
        m_NodePreviewModel:
          rid: -2
        m_State: 0
        m_InputConstantsById:
          m_KeyList:
          - Index
          - Buffer
          m_ValueList:
          - rid: 233707230134272727
          - rid: 233707254738845764
        m_InputPortInfos:
          expandedPortsById:
            m_KeyList: []
            m_ValueList: 
        m_OutputPortInfos:
          expandedPortsById:
            m_KeyList: []
            m_ValueList: 
        m_Collapsed: 0
        m_CurrentModeIndex: 0
        m_ElementColor:
          m_Color: {r: 0, g: 0, b: 0, a: 0}
          m_HasUserColor: 0
        m_Node:
          rid: 233707230134272728
    - rid: 233707230134272727
      type: {class: 'Constant`1[[System.Int32, mscorlib]]', ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Value: 0
    - rid: 233707230134272728
      type: {class: ReadBuffer, ns: Editor.Nodes.Buffers, asm: ComputeGraph.Editor}
      data: 
    - rid: 233707254738845764
      type: {class: 'Constant`1[[System.Object, mscorlib]]', ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data: 
    - rid: 233707275728453644
      type: {class: UserNodeModelImp, ns: Unity.GraphToolkit.Editor.Implementation, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Guid:
          m_Value0: 5123283793393491998
          m_Value1: 3031436441729121255
        m_HashGuid:
          serializedVersion: 2
          Hash: 1e20bc3c778f1947e73b70ec61d3112a
        m_Version: 2
        m_Position: {x: 854.87396, y: 612.4435}
        m_Title: 
        m_Tooltip: 
        m_NodePreviewModel:
          rid: -2
        m_State: 0
        m_InputConstantsById:
          m_KeyList:
          - B
          - A
          m_ValueList:
          - rid: 233707326315429890
          - rid: 233707326315429891
        m_InputPortInfos:
          expandedPortsById:
            m_KeyList: []
            m_ValueList: 
        m_OutputPortInfos:
          expandedPortsById:
            m_KeyList: []
            m_ValueList: 
        m_Collapsed: 0
        m_CurrentModeIndex: 0
        m_ElementColor:
          m_Color: {r: 0, g: 0, b: 0, a: 0}
          m_HasUserColor: 0
        m_Node:
          rid: 233707275728453646
    - rid: 233707275728453646
      type: {class: AddNode, ns: Editor.Nodes.Math.Arithmetic, asm: ComputeGraph.Editor}
      data: 
    - rid: 233707275728454027
      type: {class: VariableDeclarationModel, ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Guid:
          m_Value0: 8632439709971575005
          m_Value1: 13596975365777691978
        m_HashGuid:
          serializedVersion: 2
          Hash: ddf0d4f92d96cc774a95ea280e29b2bc
        m_Version: 2
        m_Name: Buffer
        m_UniqueId: 
        m_DataType:
          m_Identification: Editor.ComputeGraphTypes+RWBufferFloat, ComputeGraph.Editor, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
        m_IsExposed: 0
        m_Scope: 0
        m_ShowOnInspectorOnly: 0
        m_Tooltip: 
        m_InitializationValue:
          rid: 233707275728454028
        m_Modifiers: 0
        m_VariableFlags: 0
    - rid: 233707275728454028
      type: {class: 'Constant`1[[Editor.ComputeGraphTypes/RWBufferFloat, ComputeGraph.Editor]]', ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data: {}
    - rid: 233707275728454029
      type: {class: VariableNodeModelImp, ns: Unity.GraphToolkit.Editor.Implementation, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Guid:
          m_Value0: 17751357266449895811
          m_Value1: 4258246029320837714
        m_HashGuid:
          serializedVersion: 2
          Hash: 8391cb13627d59f652dae2d73354183b
        m_Version: 2
        m_Position: {x: 371.7553, y: 547.777}
        m_Title: New Variable
        m_Tooltip: 
        m_NodePreviewModel:
          rid: -2
        m_State: 0
        m_InputConstantsById:
          m_KeyList: []
          m_ValueList: []
        m_InputPortInfos:
          expandedPortsById:
            m_KeyList: []
            m_ValueList: 
        m_OutputPortInfos:
          expandedPortsById:
            m_KeyList: []
            m_ValueList: 
        m_Collapsed: 0
        m_CurrentModeIndex: 0
        m_ElementColor:
          m_Color: {r: 0, g: 0, b: 0, a: 0}
          m_HasUserColor: 0
        m_DeclarationModel:
          rid: 233707275728454027
        m_DeclarationModelHashGuid:
          serializedVersion: 2
          Hash: ddf0d4f92d96cc774a95ea280e29b2bc
    - rid: 233707275728454030
      type: {class: WireModel, ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Guid:
          m_Value0: 11251167019528449417
          m_Value1: 9742502661056021043
        m_HashGuid:
          serializedVersion: 2
          Hash: 896d9503cb2c249c33c28a5f8d523487
        m_Version: 2
        m_FromPortReference:
          m_NodeModelGuid:
            m_Value0: 17751357266449895811
            m_Value1: 4258246029320837714
          m_NodeModelHashGuid:
            serializedVersion: 2
            Hash: 8391cb13627d59f652dae2d73354183b
          m_UniqueId: MainPortName
          m_PortDirection: 2
          m_PortOrientation: 0
          m_Title: MainPortName
        m_ToPortReference:
          m_NodeModelGuid:
            m_Value0: 18052564638043145595
            m_Value1: 6207819919762491981
          m_NodeModelHashGuid:
            serializedVersion: 2
            Hash: 7b055747e49787fa4d8a099b539b2656
          m_UniqueId: RWBuffer
          m_PortDirection: 1
          m_PortOrientation: 0
          m_Title: RWBuffer
    - rid: 233707275728454037
      type: {class: WireModel, ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Guid:
          m_Value0: 17954972606505202075
          m_Value1: 5528928171543745782
        m_HashGuid:
          serializedVersion: 2
          Hash: 9bb19cc274e02cf9f6d483e5e0b2ba4c
        m_Version: 2
        m_FromPortReference:
          m_NodeModelGuid:
            m_Value0: 17751357266449895811
            m_Value1: 4258246029320837714
          m_NodeModelHashGuid:
            serializedVersion: 2
            Hash: 8391cb13627d59f652dae2d73354183b
          m_UniqueId: MainPortName
          m_PortDirection: 2
          m_PortOrientation: 0
          m_Title: MainPortName
        m_ToPortReference:
          m_NodeModelGuid:
            m_Value0: 15812093756394153039
            m_Value1: 13382450805772240484
          m_NodeModelHashGuid:
            serializedVersion: 2
            Hash: 4fa40bd17ed76fdb64c631c61a04b8b9
          m_UniqueId: Buffer
          m_PortDirection: 1
          m_PortOrientation: 0
          m_Title: Buffer
    - rid: 233707275728454038
      type: {class: WireModel, ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Guid:
          m_Value0: 17013978429587401452
          m_Value1: 17852264745276625699
        m_HashGuid:
          serializedVersion: 2
          Hash: ec2ab7df3ccb1dec2353715233fcbff7
        m_Version: 2
        m_FromPortReference:
          m_NodeModelGuid:
            m_Value0: 15812093756394153039
            m_Value1: 13382450805772240484
          m_NodeModelHashGuid:
            serializedVersion: 2
            Hash: 4fa40bd17ed76fdb64c631c61a04b8b9
          m_UniqueId: Out
          m_PortDirection: 2
          m_PortOrientation: 0
          m_Title: Out
        m_ToPortReference:
          m_NodeModelGuid:
            m_Value0: 5123283793393491998
            m_Value1: 3031436441729121255
          m_NodeModelHashGuid:
            serializedVersion: 2
            Hash: 1e20bc3c778f1947e73b70ec61d3112a
          m_UniqueId: A
          m_PortDirection: 1
          m_PortOrientation: 0
          m_Title: A
    - rid: 233707275728454041
      type: {class: WireModel, ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Guid:
          m_Value0: 4855327528933556453
          m_Value1: 1830235595650083997
        m_HashGuid:
          serializedVersion: 2
          Hash: e58042b6a99661439dacffc5934d6619
        m_Version: 2
        m_FromPortReference:
          m_NodeModelGuid:
            m_Value0: 5123283793393491998
            m_Value1: 3031436441729121255
          m_NodeModelHashGuid:
            serializedVersion: 2
            Hash: 1e20bc3c778f1947e73b70ec61d3112a
          m_UniqueId: Out
          m_PortDirection: 2
          m_PortOrientation: 0
          m_Title: Out
        m_ToPortReference:
          m_NodeModelGuid:
            m_Value0: 18052564638043145595
            m_Value1: 6207819919762491981
          m_NodeModelHashGuid:
            serializedVersion: 2
            Hash: 7b055747e49787fa4d8a099b539b2656
          m_UniqueId: Value
          m_PortDirection: 1
          m_PortOrientation: 0
          m_Title: Value
    - rid: 233707326315429888
      type: {class: 'Constant`1[[System.Single, mscorlib]]', ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Value: 0
    - rid: 233707326315429889
      type: {class: 'Constant`1[[Editor.ComputeGraphTypes/RWBufferFloat, ComputeGraph.Editor]]', ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data: {}
    - rid: 233707326315429890
      type: {class: 'Constant`1[[System.Single, mscorlib]]', ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Value: 2
    - rid: 233707326315429891
      type: {class: 'Constant`1[[System.Single, mscorlib]]', ns: Unity.GraphToolkit.Editor, asm: UnityEditor.GraphToolkitModule}
      data:
        m_Value: 0
